In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv(r"C:\\Users\\CCEE\\Desktop\\Employee data.csv")
df.head()

,id,gender,bdate,educ,jobcat,salary,salbegin,jobtime,prevexp,minority
0,1.0,Male,1952-02-03,15,Manager,57000.0,27000.0,98.0,144.0,No
1,2.0,Male,1958-05-23,16,Clerical,40200.0,18750.0,98.0,36.0,No
2,3.0,Female,1929-07-26,12,Clerical,21450.0,12000.0,98.0,381.0,No
3,4.0,Female,1947-04-15,8,Clerical,21900.0,13200.0,98.0,190.0,No
4,5.0,Male,1955-02-09,15,Clerical,45000.0,21000.0,98.0,138.0,No

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 474 entries, 0 to 473
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        474 non-null    float64
 1   gender    474 non-null    object
 2   bdate     473 non-null    object
 3   educ      474 non-null    int64
 4   jobcat    474 non-null    object
 5   salary    474 non-null    float64
 6   salbegin  474 non-null    float64
 7   jobtime   474 non-null    float64
 8   prevexp   474 non-null    object
 9   minority  474 non-null    object
dtypes: float64(4), int64(1), object(5)
memory usage: 37.2+ KB

In [5]:
df.describe()

               id        educ         salary      salbegin     jobtime
count  474.000000  474.000000     474.000000    474.000000  474.000000
mean   237.500000   13.491561   34419.567511  17016.086498   81.109705
std    136.976275    2.884846   17075.661465   7870.638154   10.060945
min      1.000000    8.000000   15750.000000   9000.000000   63.000000
25%    119.250000   12.000000   24000.000000  12487.500000   72.000000
50%    237.500000   12.000000   28875.000000  15000.000000   81.000000
75%    355.750000   15.000000   36937.500000  17490.000000   90.000000
max    474.000000   21.000000  135000.000000  79980.000000   98.000000

In [6]:
df.columns

Index(['id', 'gender', 'bdate', 'educ', 'jobcat', 'salary', 'salbegin',
       'jobtime', 'prevexp', 'minority'],
      dtype='object')

In [7]:
df['educ'].unique()

array([15, 16, 12,  8, 19, 17, 18, 14, 20, 21], dtype=int64)

In [8]:
df.jobcat.unique()

array(['Manager', 'Clerical', 'Custodial'], dtype=object)

In [9]:
df.gender.unique()

array(['Male', 'Female'], dtype=object)

In [10]:
df.jobtime.unique()

array([98., 97., 96., 95., 94., 93., 92., 91., 90., 89., 88., 87., 86.,
       85., 84., 83., 82., 81., 80., 79., 78., 77., 76., 75., 74., 73.,
       72., 71., 70., 69., 68., 67., 66., 65., 64., 63.])

In [11]:
df.minority.unique()

array(['No', 'Yes'], dtype=object)

In [12]:
df.groupby('jobcat')['minority'].value_counts()

jobcat     minority
Clerical   No          276
           Yes          87
Custodial  No           14
           Yes          13
Manager    No           80
           Yes           4
Name: count, dtype: int64

In [13]:
df.head(2)

,id,gender,bdate,educ,jobcat,salary,salbegin,jobtime,prevexp,minority
0,1.0,Male,1952-02-03,15,Manager,57000.0,27000.0,98.0,144.0,No
1,2.0,Male,1958-05-23,16,Clerical,40200.0,18750.0,98.0,36.0,No

# Drop Irrelevant Features

In [15]:
df = df.drop(columns=['id'])

In [16]:
df.head(1)

,gender,bdate,educ,jobcat,salary,salbegin,jobtime,prevexp,minority
0,Male,1952-02-03,15,Manager,57000.0,27000.0,98.0,144.0,No

# Convert date and extract features

In [18]:
df['bdate'] = pd.to_datetime(df['bdate'])

current_year = pd.Timestamp.now().year

df['age'] = current_year - df['bdate'].dt.year

In [19]:
df = df.drop(columns=['bdate'])

In [20]:
df.head(1)

  gender  educ   jobcat   salary  salbegin  jobtime prevexp minority   age
0   Male    15  Manager  57000.0   27000.0     98.0   144.0       No  74.0

In [21]:
# Convert obje to num
df['prevexp'] = pd.to_numeric(df['prevexp'], errors='coerce')

In [22]:
df.isnull().sum()

gender       0
educ         0
jobcat       0
salary       0
salbegin     0
jobtime      0
prevexp     24
minority     0
age          1
dtype: int64

In [23]:
df.dtypes

gender       object
educ          int64
jobcat       object
salary      float64
salbegin    float64
jobtime     float64
prevexp     float64
minority     object
age         float64
dtype: object

In [24]:
df.head(3)

   gender  educ    jobcat   salary  salbegin  jobtime  prevexp minority   age
0    Male    15   Manager  57000.0   27000.0     98.0    144.0       No  74.0
1    Male    16  Clerical  40200.0   18750.0     98.0     36.0       No  68.0
2  Female    12  Clerical  21450.0   12000.0     98.0    381.0       No  97.0

## Handle missing values

In [26]:
from sklearn.impute import SimpleImputer
num_cols = ['educ', 'salary', 'salbegin', 'jobtime', 'prevexp', 'age']

num_imputer = SimpleImputer(strategy='median')

df[num_cols] = num_imputer.fit_transform(df[num_cols])

In [27]:
cat_cols = ['gender', 'jobcat', 'minority']

cat_imputer = SimpleImputer(strategy='most_frequent')

df[cat_cols] = cat_imputer.fit_transform(df[cat_cols])

In [28]:
df.isnull().sum()

gender      0
educ        0
jobcat      0
salary      0
salbegin    0
jobtime     0
prevexp     0
minority    0
age         0
dtype: int64

In [29]:
import numpy as np

## Handle outliers (IQR capping)

In [31]:
for col in ['salary', 'salbegin', 'prevexp', 'jobtime']: #10k, 10k, 10k, 50k-120k, 170k
    
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR #10k
    upper = Q3 + 1.5 * IQR #170k
    
    df[col] = np.clip(df[col], lower, upper)

# Feature Engineering

### Salary growth feature

In [34]:
df['salary_growth'] = df['salary'] - df['salbegin']

### Experience ratio feature

In [36]:
df['experience_ratio'] = df['prevexp'] / (df['jobtime'] + 1)

### Education category (binning)

In [38]:
df['educ_level'] = pd.cut(df['educ'],
                          bins=[0,12,16,25],
                          labels=['School','Undergrad','Graduate'])

In [39]:
df.head(3)

,gender,educ,jobcat,salary,salbegin,jobtime,prevexp,minority,age,salary_growth,experience_ratio,educ_level
0,Male,15.0,Manager,56343.75,24993.75,98.0,144.000,No,74.0,31350.0,1.454545,Undergrad
1,Male,16.0,Clerical,40200.00,18750.00,98.0,36.000,No,68.0,21450.0,0.363636,Undergrad
2,Female,12.0,Clerical,21450.00,12000.00,98.0,309.375,No,97.0,9450.0,3.125000,School

### Age group feature

In [41]:
df.age.max()

97.0

In [42]:
df.age.min()

55.0

In [43]:
df['age_group'] = pd.cut(df['age'],
                         bins=[55,75,85,97],
                         labels=['Young','Mid','Senior'])

In [44]:
df.head(3)

,gender,educ,jobcat,salary,salbegin,jobtime,prevexp,minority,age,salary_growth,experience_ratio,educ_level,age_group
0,Male,15.0,Manager,56343.75,24993.75,98.0,144.000,No,74.0,31350.0,1.454545,Undergrad,Young
1,Male,16.0,Clerical,40200.00,18750.00,98.0,36.000,No,68.0,21450.0,0.363636,Undergrad,Young
2,Female,12.0,Clerical,21450.00,12000.00,98.0,309.375,No,97.0,9450.0,3.125000,School,Senior

# Feature Scaling

In [46]:
num_col = df.select_dtypes(include='number').columns
num_col

Index(['educ', 'salary', 'salbegin', 'jobtime', 'prevexp', 'age',
       'salary_growth', 'experience_ratio'],
      dtype='object')

In [47]:
for col in num_col:
    print(col, 'Min=',df[col].min(), 'Max =',df[col].max())

educ Min= 8.0 Max = 21.0
salary Min= 15750.0 Max = 56343.75
salbegin Min= 9000.0 Max = 24993.75
jobtime Min= 63.0 Max = 98.0
prevexp Min= 2.0 Max = 309.375
age Min= 55.0 Max = 97.0
salary_growth Min= 5550.0 Max = 40593.75
experience_ratio Min= 0.02666666666666667 Max = 4.6875

In [48]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
scaler = StandardScaler()
df[num_col] = scaler.fit_transform(df[num_col])

In [49]:
df.head()

,gender,educ,jobcat,salary,salbegin,jobtime,prevexp,minority,age,salary_growth,experience_ratio,educ_level,age_group
0,Male,0.523436,Manager,2.043408,2.026817,1.680572,0.545342,No,0.368953,1.860060,0.251387,Undergrad,Young
1,Male,0.870441,Clerical,0.663968,0.644150,1.680572,-0.645015,No,-0.141160,0.612602,-0.708583,Undergrad,Young
2,Female,-0.517579,Clerical,-0.938168,-0.850624,1.680572,2.368076,No,2.324389,-0.899468,1.721342,School,Senior
3,Female,-1.905600,Clerical,-0.899717,-0.584886,1.680572,1.052346,No,0.794048,-0.993973,0.660264,School,Mid
4,Male,0.523436,Clerical,1.074115,1.142408,1.680572,0.479211,No,0.113897,0.933917,0.198056,Undergrad,Young

## Encoding categorical variables

Label Encoding
One Hot Encoding
Ordinal Encoding
Binary Encoding

gender      → nominal
jobcat      → nominal
minority    → binary
educ_level  → ordinal
age_group   → ordinal

In [52]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder

In [53]:
df.gender.unique()

array(['Male', 'Female'], dtype=object)

In [54]:
df.minority.unique()

array(['No', 'Yes'], dtype=object)

In [55]:
#Binary encoding
df['gender'] = df['gender'].map({'Male':0, 'Female':1})
df['minority'] = df['minority'].map({'No':0, 'Yes':1})

### OR

In [57]:
# Label Encoding
le = LabelEncoder()
df['age_group'] = le.fit_transform(df['age_group'])
df['jobcat'] = le.fit_transform(df['jobcat'])

### OR

In [59]:
# Ordinal Encoding
oe = OrdinalEncoder()
df['educ_level'] = oe.fit_transform(df[['educ_level']])

In [60]:
df.head(2)

,gender,educ,jobcat,salary,salbegin,jobtime,prevexp,minority,age,salary_growth,experience_ratio,educ_level,age_group
0,0,0.523436,2,2.043408,2.026817,1.680572,0.545342,0,0.368953,1.860060,0.251387,2.0,2
1,0,0.870441,0,0.663968,0.644150,1.680572,-0.645015,0,-0.141160,0.612602,-0.708583,2.0,2

### Train Test Aplit

In [62]:
x = df.drop('salary', axis=1)
y = df['salary']

In [63]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [65]:
df.fillna(0.0, inplace=True)

In [67]:
df.isnull().sum()

gender              0
educ                0
jobcat              0
salary              0
salbegin            0
jobtime             0
prevexp             0
minority            0
age                 0
salary_growth       0
experience_ratio    0
educ_level          0
age_group           0
dtype: int64

In [85]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [87]:
y_pred = model.predict(x_test)

In [91]:
from sklearn.metrics import r2_score, mean_squared_error
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(mse)
print(r2)

7.107616663650466e-31
1.0